# Generated by Django 5.0.6 on 2024-06-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_total_orders_product_total_sales_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mockup_image',
            field=models.ImageField(blank=True, null=True, upload_to='mockups'),
        ),
        migrations.AddField(
            model_name='product',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews'),
        ),
    ]
