# Generated by Django 5.0.6 on 2024-06-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_mockup_image_product_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
